# Generated by Django 4.2.1 on 2024-09-28 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TableMeta",
            fields=[
                (
                    "name",
                    models.CharField(max_length=300, primary_key=True, serialize=False),
                ),
                ("topic", models.CharField(max_length=600)),
                ("field_bytes", models.BinaryField(default=b"{}")),
            ],
            options={
                "unique_together": {("name", "topic")},
            },
        ),
    ]
