# Generated by Django 4.2.1 on 2025-02-04 00:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tables", "0002_my_test_"),
    ]

    operations = [
        migrations.CreateModel(
            name="my_table_",
            fields=[
                ("id", models.CharField()),
            ],
        ),
        migrations.DeleteModel(
            name="my_test_",
        ),
    ]
