# Generated by Django 4.2.1 on 2025-02-04 00:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tables", "0003_my_table__delete_my_test_"),
    ]

    operations = [
        migrations.CreateModel(
            name="other_table_",
            fields=[
                ("id", models.CharField()),
            ],
        ),
    ]
