# Generated by Django 4.2.1 on 2025-02-04 01:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tables", "0004_other_table_"),
    ]

    operations = [
        migrations.DeleteModel(
            name="other_table_",
        ),
    ]
