# Generated by Django 4.0.4 on 2023-02-09 01:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                ("topic", models.TextField(primary_key=True, serialize=False)),
                ("data", models.BinaryField(default=None, null=True)),
                ("qos", models.PositiveIntegerField(default=None, null=True)),
            ],
        ),
    ]
